# Generated by Django 3.2.8 on 2021-11-29 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminBluemoon', '0001_initial'),
        ('store', '0007_auto_20211120_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminBluemoon.offer'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_offer_price',
            field=models.IntegerField(null=True),
        ),
    ]
