# Generated by Django 3.2.8 on 2021-11-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminBluemoon', '0001_initial'),
        ('store', '0008_auto_20211129_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminBluemoon.offer'),
        ),
    ]
