# Generated by Django 3.2.8 on 2021-12-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.UUIDField()),
                ('minimum_rate', models.IntegerField()),
                ('percentage', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('expiry_time', models.TimeField()),
            ],
        ),
    ]
