# Generated by Django 3.2.8 on 2021-12-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_usedcoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='photos/banners')),
                ('tag_line', models.CharField(max_length=250)),
                ('heading', models.CharField(max_length=250)),
                ('offer_percentage', models.CharField(max_length=250)),
                ('starting_price', models.IntegerField()),
            ],
        ),
    ]
