# Generated by Django 3.2.8 on 2021-12-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='heading',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='offer_percentage',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='starting_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='tag_line',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
