# Generated by Django 3.2.8 on 2021-12-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20211206_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
