# Generated by Django 3.2.8 on 2021-11-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
