# Generated by Django 3.2.9 on 2021-11-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20211123_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='variation',
            field=models.CharField(blank=True, default='size_m', max_length=6, null=True),
        ),
    ]
