# Generated by Django 3.2.9 on 2021-11-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('descrption', models.TextField(blank=True)),
                ('category_image', models.ImageField(blank=True, upload_to='photos/categories')),
            ],
        ),
    ]
